#!/usr/bin/env sh

. ${HOME}/.bashrc

. ${HOME}/.alias

if [ -d "$HOME/etc/bash_completion.d" ]; then
	. $HOME/etc/bash_completion.d/*.bash
fi

if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

if [ -f "$HOME/.work_bashrc" ]; then
	. $HOME/.work_bashrc
fi

. "$HOME/.local/bin/env"
